export type Job = {
  id: string;
  title: string;
  slug: string;
  company_name: string | null;
  company_logo_url?: string | null;
  company_logo?: string | null;
  industry: string | null;
  job_function: string | null;
  experience_level: string | null;
  eligibility: string | null;
  country: string | null;
  state_region: string | null;
  city: string | null;
  location_display: string | null;
  work_type: string | null;
  employment_type: string | null;
  salary_min: number | null;
  salary_max: number | null;
  salary_currency: string | null;
  salary_display: string | null;
  description: string | null;
  source_name: string | null;
  original_job_url: string;
  posted_at: string | null;
  fetched_at: string | null;
  status: string | null;
  is_visa_sponsorship?: boolean | null;
  is_featured?: boolean | null;
};