"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import jsPDF from "jspdf";
import {
  Brain,
  Send,
  Sparkles,
  RotateCcw,
  Trophy,
  Download,
} from "lucide-react";
import { supabaseBrowser } from "@/lib/supabase-browser";

type InterviewSession = {
  id: string;
  target_role: string | null;
  question: string | null;
  user_answer: string | null;
  feedback: string | null;
  score: number | null;
  created_at: string | null;
};

type JobContext = {
  id: string;
  title: string | null;
  company_name: string | null;
  description: string | null;
  requirements: string | null;
  responsibilities: string | null;
};

type InterviewRound = {
  round: number;
  question: string;
  answer: string;
};

type FinalAssessment = {
  overall_score?: number;
  communication_score?: number;
  technical_score?: number;
  confidence_score?: number;
  problem_solving_score?: number;
  role_fit_score?: number;
  recommendation?: string;
  strengths?: string;
  improvements?: string;
  final_feedback?: string;
};

export default function InterviewIQPage() {
  const [userId, setUserId] = useState("");
  const [targetRole, setTargetRole] = useState("Business Analyst");
  const [companyName, setCompanyName] = useState("");
  const [jobContext, setJobContext] = useState<JobContext | null>(null);
  const [mode, setMode] = useState<"single" | "multi">("single");

  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [feedback, setFeedback] = useState("");
  const [score, setScore] = useState<number | null>(null);

  const [rounds, setRounds] = useState<InterviewRound[]>([]);
  const [currentRound, setCurrentRound] = useState(0);
  const [maxRounds, setMaxRounds] = useState(5);
  const [finalAssessment, setFinalAssessment] =
    useState<FinalAssessment | null>(null);

  const [sessions, setSessions] = useState<InterviewSession[]>([]);
  const [loading, setLoading] = useState(true);
  const [starting, setStarting] = useState(false);
  const [reviewing, setReviewing] = useState(false);
  const [message, setMessage] = useState("");

  async function loadSessions(currentUserId: string) {
    const { data } = await supabaseBrowser
      .from("interview_iq_sessions")
      .select("id,target_role,question,user_answer,feedback,score,created_at")
      .eq("user_id", currentUserId)
      .order("created_at", { ascending: false })
      .limit(10);

    setSessions((data || []) as InterviewSession[]);
  }

  function downloadMultiRoundReport() {
    if (!finalAssessment) {
      setMessage("Please complete the multi-round interview first.");
      return;
    }

    const doc = new jsPDF();
    const margin = 15;
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxWidth = pageWidth - margin * 2;
    let y = 18;

    function addText(title: string, content: string) {
      if (y > 260) {
        doc.addPage();
        y = 18;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text(title, margin, y);

      y += 7;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);

      const lines = doc.splitTextToSize(content || "Not available.", maxWidth);
      doc.text(lines, margin, y);

      y += lines.length * 5 + 8;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("Chumcred Multi-Round InterviewIQ Report", margin, y);

    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Generated by Chumcred Global Job Bank", margin, y);

    y += 10;
    doc.line(margin, y, pageWidth - margin, y);

    y += 12;
    addText("Target Role", targetRole);
    addText("Company", companyName || "Not specified");

    addText(
      "Overall Assessment",
      `Overall Score: ${finalAssessment.overall_score || 0}%
Communication: ${finalAssessment.communication_score || 0}%
Technical: ${finalAssessment.technical_score || 0}%
Confidence: ${finalAssessment.confidence_score || 0}%
Problem Solving: ${finalAssessment.problem_solving_score || 0}%
Role Fit: ${finalAssessment.role_fit_score || 0}%
Recommendation: ${finalAssessment.recommendation || "Not available"}`
    );

    rounds.forEach((round) => {
      addText(
        `Round ${round.round}`,
        `Question:
${round.question}

Candidate Answer:
${round.answer || "Not answered."}`
      );
    });

    addText("Strengths", finalAssessment.strengths || "");
    addText("Improvements", finalAssessment.improvements || "");
    addText("Final Feedback", finalAssessment.final_feedback || "");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("Generated by Chumcred InterviewIQ | jobs.chumcred.com", margin, 285);

    doc.save(`Multi_Round_InterviewIQ_Report_${Date.now()}.pdf`);
  }

  async function loadJobContext(jobId: string) {
    const { data } = await supabaseBrowser
      .from("jobs")
      .select("id,title,company_name,description,requirements,responsibilities")
      .eq("id", jobId)
      .maybeSingle();

    if (data) {
      const job = data as JobContext;
      setJobContext(job);
      setCompanyName(job.company_name || "");

      setTargetRole(
        job.company_name
          ? `${job.title || "Job"} at ${job.company_name}`
          : job.title || "Job Interview"
      );
    }
  }

  useEffect(() => {
    async function init() {
      try {
        const { data: userData } = await supabaseBrowser.auth.getUser();
        const user = userData.user;

        if (!user) {
          window.location.href = "/login";
          return;
        }

        if (typeof window !== "undefined") {
          const params = new URLSearchParams(window.location.search);
          const jobId = params.get("job_id");
          const roleFromUrl = params.get("role");
          const companyFromUrl = params.get("company");
          const modeFromUrl = params.get("mode");

          if (modeFromUrl === "multi") setMode("multi");

          if (jobId) {
            await loadJobContext(jobId);
          } else if (roleFromUrl) {
            setTargetRole(
              companyFromUrl ? `${roleFromUrl} at ${companyFromUrl}` : roleFromUrl
            );
            setCompanyName(companyFromUrl || "");
          }
        }

        setUserId(user.id);

        try {
          await loadSessions(user.id);
        } catch (sessionError) {
          console.error("InterviewIQ sessions load error:", sessionError);
        }
      } catch (error) {
        console.error("InterviewIQ Init Error:", error);
        setMessage("InterviewIQ loaded with limited history. You can continue.");
      } finally {
        setLoading(false);
      }
    }

    init();
  }, []);

  function resetInterview() {
    setQuestion("");
    setAnswer("");
    setFeedback("");
    setScore(null);
    setRounds([]);
    setCurrentRound(0);
    setFinalAssessment(null);
    setMessage("");
  }

  async function startSingleInterview() {
    if (!userId || !targetRole.trim()) return;

    setStarting(true);
    setMessage("");
    setQuestion("");
    setAnswer("");
    setFeedback("");
    setScore(null);

    const response = await fetch("/api/interview-iq/question", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        user_id: userId,
        target_role: targetRole,
        job_context: jobContext,
      }),
    });

    const data = await response.json();

    if (!response.ok || data.status === "error") {
      setMessage(data.message || data.error || "Unable to generate question.");
      setStarting(false);
      return;
    }

    setQuestion(data.question || "");
    setStarting(false);
  }

  async function submitSingleAnswer() {
    if (!userId || !targetRole || !question || !answer.trim()) {
      setMessage("Please enter your answer before submitting.");
      return;
    }

    setReviewing(true);
    setMessage("");

    const response = await fetch("/api/interview-iq/review", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        user_id: userId,
        target_role: targetRole,
        question,
        answer,
        job_context: jobContext,
      }),
    });

    const data = await response.json();

    if (!response.ok || data.status === "error") {
      setMessage(data.message || data.error || "Unable to review answer.");
      setReviewing(false);
      return;
    }

    setFeedback(data.review?.feedback || "");
    setScore(data.review?.score || 0);
    await loadSessions(userId);
    setReviewing(false);
  }

  async function startMultiRoundInterview() {
    if (!targetRole.trim()) return;

    setStarting(true);
    setMessage("");
    setAnswer("");
    setRounds([]);
    setFinalAssessment(null);

    const response = await fetch("/api/interview-iq/start-session", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        target_role: targetRole,
        company_name: companyName,
        job_context: jobContext,
      }),
    });

    const data = await response.json();

    if (!response.ok || data.status === "error") {
      setMessage(data.message || data.error || "Unable to start interview.");
      setStarting(false);
      return;
    }

    setQuestion(data.question || "");
    setRounds(data.rounds || []);
    setCurrentRound(data.round || 1);
    setMaxRounds(data.max_rounds || 5);
    setStarting(false);
  }

  async function submitMultiRoundAnswer() {
    if (!answer.trim()) {
      setMessage("Please enter your answer before moving to the next round.");
      return;
    }

    setReviewing(true);
    setMessage("");

    if (currentRound >= maxRounds) {
      const completedRounds = [...rounds];
      completedRounds[completedRounds.length - 1] = {
        ...completedRounds[completedRounds.length - 1],
        answer,
      };

      const response = await fetch("/api/interview-iq/end-session", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          target_role: targetRole,
          company_name: companyName,
          job_context: jobContext,
          rounds: completedRounds,
        }),
      });

      const data = await response.json();

      if (!response.ok || data.status === "error") {
        setMessage(data.message || data.error || "Unable to end interview.");
        setReviewing(false);
        return;
      }

      setRounds(completedRounds);
      setFinalAssessment(data.assessment || null);
      setQuestion("");
      setAnswer("");
      setReviewing(false);
      return;
    }

    const response = await fetch("/api/interview-iq/next-question", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        target_role: targetRole,
        company_name: companyName,
        job_context: jobContext,
        rounds,
        answer,
      }),
    });

    const data = await response.json();

    if (!response.ok || data.status === "error") {
      setMessage(data.message || data.error || "Unable to generate next question.");
      setReviewing(false);
      return;
    }

    setRounds(data.rounds || []);
    setCurrentRound(data.round || currentRound + 1);
    setQuestion(data.question || "");
    setAnswer("");
    setReviewing(false);
  }

  if (loading) {
    return (
      <main className="mx-auto max-w-6xl px-6 py-16">
        <p className="text-slate-600">Loading InterviewIQ...</p>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-6xl px-6 py-12">
      <Link href="/dashboard" className="text-sm font-semibold text-blue-700">
        ← Back to Dashboard
      </Link>

      <section className="mt-8 rounded-3xl bg-slate-950 p-8 text-white shadow-sm">
        <div className="flex items-center gap-4">
          <div className="rounded-2xl bg-blue-600 p-3">
            <Brain size={34} />
          </div>

          <div>
            <p className="text-sm font-semibold uppercase tracking-widest text-blue-300">
              InterviewIQ
            </p>

            <h1 className="mt-2 text-4xl font-bold">
              Practice Job Interviews with AI
            </h1>

            <p className="mt-3 max-w-3xl text-slate-300">
              Choose single-question practice or a premium multi-round adaptive interview.
            </p>

            <Link
              href="/interview-iq/video"
              className="mt-6 inline-flex rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700"
            >
              Open Premium Video InterviewIQ
            </Link>
          </div>
        </div>
      </section>

      {message && (
        <div className="mt-6 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">
          {message}
        </div>
      )}

      {jobContext && (
        <section className="mt-8 rounded-3xl border bg-blue-50 p-6">
          <p className="text-sm font-semibold uppercase tracking-widest text-blue-700">
            Job-Aware Interview Mode
          </p>
          <h2 className="mt-2 text-2xl font-bold text-slate-900">
            {jobContext.title}
          </h2>
          <p className="mt-1 text-slate-700">
            {jobContext.company_name || "Company not stated"}
          </p>
        </section>
      )}

      <section className="mt-8 rounded-3xl border bg-white p-6 shadow-sm">
        <h2 className="text-xl font-bold text-slate-900">Interview Mode</h2>

        <div className="mt-5 flex flex-wrap gap-3">
          <button
            onClick={() => {
              resetInterview();
              setMode("single");
            }}
            className={`rounded-xl px-5 py-3 font-semibold ${
              mode === "single"
                ? "bg-blue-600 text-white"
                : "border text-slate-700 hover:bg-slate-50"
            }`}
          >
            Single InterviewIQ
          </button>

          <button
            onClick={() => {
              resetInterview();
              setMode("multi");
            }}
            className={`rounded-xl px-5 py-3 font-semibold ${
              mode === "multi"
                ? "bg-slate-900 text-white"
                : "border text-slate-700 hover:bg-slate-50"
            }`}
          >
            Multi-Round InterviewIQ
          </button>
        </div>
      </section>

      <section className="mt-8 grid gap-6 lg:grid-cols-3">
        <div className="rounded-3xl border bg-white p-6 shadow-sm">
          <h2 className="text-xl font-bold text-slate-900">Interview Setup</h2>

          <label className="mt-5 block text-sm font-semibold text-slate-700">
            Target Role
          </label>

          <input
            value={targetRole}
            onChange={(e) => setTargetRole(e.target.value)}
            className="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-blue-600"
          />

          {mode === "multi" && (
            <>
              <label className="mt-5 block text-sm font-semibold text-slate-700">
                Company Name
              </label>

              <input
                value={companyName}
                onChange={(e) => setCompanyName(e.target.value)}
                placeholder="Example: Access Bank"
                className="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-blue-600"
              />
            </>
          )}

          <button
            onClick={mode === "single" ? startSingleInterview : startMultiRoundInterview}
            disabled={starting}
            className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700 disabled:opacity-60"
          >
            <Sparkles size={18} />
            {starting
              ? "Starting..."
              : mode === "single"
              ? "Start Interview"
              : "Start Multi-Round Interview"}
          </button>

          <button
            onClick={resetInterview}
            className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border px-5 py-3 font-semibold text-slate-700 hover:bg-slate-50"
          >
            <RotateCcw size={18} />
            Reset
          </button>
        </div>

        <div className="rounded-3xl border bg-white p-6 shadow-sm lg:col-span-2">
          <h2 className="text-xl font-bold text-slate-900">
            {mode === "multi"
              ? `Question ${currentRound || 1} of ${maxRounds}`
              : "Current Question"}
          </h2>

          {question ? (
            <>
              <div className="mt-5 rounded-2xl bg-slate-50 p-5">
                <p className="text-lg font-semibold text-slate-900">
                  {question}
                </p>
              </div>

              <label className="mt-6 block text-sm font-semibold text-slate-700">
                Your Answer
              </label>

              <textarea
                value={answer}
                onChange={(e) => setAnswer(e.target.value)}
                rows={7}
                placeholder="Type your interview answer here."
                className="mt-2 w-full rounded-2xl border px-4 py-3 outline-none focus:border-blue-600"
              />

              <button
                onClick={
                  mode === "single" ? submitSingleAnswer : submitMultiRoundAnswer
                }
                disabled={reviewing}
                className="mt-5 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-6 py-3 font-semibold text-white hover:bg-blue-700 disabled:opacity-60"
              >
                <Send size={18} />
                {reviewing
                  ? "Processing..."
                  : mode === "single"
                  ? "Submit Answer"
                  : currentRound >= maxRounds
                  ? "Finish Interview"
                  : "Submit & Continue"}
              </button>
            </>
          ) : finalAssessment ? (
            <div className="mt-5 rounded-2xl bg-green-50 p-6 text-green-800">
              Interview completed. See final assessment below.
            </div>
          ) : (
            <div className="mt-5 rounded-2xl border border-dashed p-8 text-center text-slate-600">
              Start an interview to generate your first question.
            </div>
          )}
        </div>
      </section>

      {feedback && mode === "single" && (
        <section className="mt-8 rounded-3xl border bg-white p-8 shadow-sm">
          <p className="text-sm font-semibold uppercase tracking-widest text-blue-700">
            AI Interview Feedback
          </p>

          <h2 className="mt-2 text-3xl font-bold text-slate-900">
            Score: {score || 0}
          </h2>

          <div className="mt-6 rounded-2xl bg-slate-50 p-5">
            <p className="whitespace-pre-line text-sm leading-7 text-slate-700">
              {feedback}
            </p>
          </div>
        </section>
      )}

      {rounds.length > 0 && mode === "multi" && (
        <section className="mt-8 rounded-3xl border bg-white p-8 shadow-sm">
          <h2 className="text-2xl font-bold text-slate-900">
            Interview Rounds
          </h2>

          <div className="mt-5 space-y-4">
            {rounds.map((round) => (
              <div key={round.round} className="rounded-2xl bg-slate-50 p-5">
                <p className="text-sm font-semibold text-blue-700">
                  Round {round.round}
                </p>
                <p className="mt-2 font-semibold text-slate-900">
                  {round.question}
                </p>
                {round.answer && (
                  <p className="mt-3 text-sm text-slate-600">
                    {round.answer}
                  </p>
                )}
              </div>
            ))}
          </div>
        </section>
      )}

      {finalAssessment && (
        <section className="mt-8 rounded-3xl border bg-white p-8 shadow-sm">
          <div className="flex items-center gap-3">
            <Trophy className="text-amber-600" />
            <p className="text-sm font-semibold uppercase tracking-widest text-blue-700">
              Final Interview Assessment
            </p>
          </div>

          <h2 className="mt-3 text-4xl font-bold text-slate-900">
            Overall Score: {finalAssessment.overall_score || 0}%
          </h2>

          <button
            onClick={downloadMultiRoundReport}
            className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700"
          >
            <Download size={18} />
            Download Multi-Round Interview Report
          </button>

          <p className="mt-3 text-lg font-semibold text-slate-700">
            Recommendation: {finalAssessment.recommendation || "Not available"}
          </p>

          <div className="mt-6 grid gap-4 md:grid-cols-5">
            <ScoreBox title="Communication" value={finalAssessment.communication_score} />
            <ScoreBox title="Technical" value={finalAssessment.technical_score} />
            <ScoreBox title="Confidence" value={finalAssessment.confidence_score} />
            <ScoreBox title="Problem Solving" value={finalAssessment.problem_solving_score} />
            <ScoreBox title="Role Fit" value={finalAssessment.role_fit_score} />
          </div>

          <div className="mt-8 grid gap-5 md:grid-cols-3">
            <TextBox title="Strengths" content={finalAssessment.strengths} />
            <TextBox title="Improvements" content={finalAssessment.improvements} />
            <TextBox title="Final Feedback" content={finalAssessment.final_feedback} />
          </div>
        </section>
      )}

      {sessions.length > 0 && (
        <section className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Previous Interview Practice
          </h2>

          <div className="mt-5 space-y-4">
            {sessions.map((session) => (
              <div
                key={session.id}
                className="rounded-3xl border bg-white p-6 shadow-sm"
              >
                <p className="text-sm font-semibold uppercase tracking-widest text-blue-700">
                  {session.target_role || "Interview Practice"}
                </p>

                <h3 className="mt-2 text-lg font-bold text-slate-900">
                  {session.question}
                </h3>

                <p className="mt-2 text-sm text-slate-500">
                  Score: {session.score || 0}
                </p>
              </div>
            ))}
          </div>
        </section>
      )}
    </main>
  );
}

function ScoreBox({ title, value }: { title: string; value?: number }) {
  return (
    <div className="rounded-2xl bg-blue-50 p-4 text-center text-blue-700">
      <p className="text-2xl font-bold">{value || 0}</p>
      <p className="mt-1 text-xs font-semibold">{title}</p>
    </div>
  );
}

function TextBox({ title, content }: { title: string; content?: string }) {
  return (
    <div className="rounded-2xl bg-slate-50 p-5">
      <h3 className="font-bold text-slate-900">{title}</h3>
      <p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-700">
        {content || "Not available."}
      </p>
    </div>
  );
}